"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import {
  AlertCircle,
  CheckCircle2,
  ChevronDown,
  ChevronUp,
  Download,
  FileText,
  Mic,
  RotateCcw,
  Save,
  Sparkles,
  Square,
} from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Separator } from "@/components/ui/separator";
import { cn } from "@/lib/utils";
import type { SoapNote } from "@/app/api/soap-note/route";
import type { ClinicalExtract } from "@/app/api/clinical-extract/route";
import type { PatientHistory } from "@/lib/types/cdss";

// ── Recording status ──────────────────────────────────────────────────────────

type RecordingStatus =
  | "idle"
  | "recording"
  | "stopped"
  | "generating"
  | "ready"
  | "saved"
  | "error";

// ── Clinical history sections ─────────────────────────────────────────────────

const HISTORY_SECTIONS: {
  key: keyof Omit<SoapNote, "summary">;
  label: string;
  abbr: string;
  color: string;
  hint: string;
}[] = [
  {
    key: "co",
    label: "Complains Of",
    abbr: "CO",
    color: "border-l-blue-400",
    hint: "Presenting complaint in patient's own words",
  },
  {
    key: "hpc",
    label: "History of Present Complaint",
    abbr: "HPC",
    color: "border-l-violet-400",
    hint: "Onset, duration, severity, cyclical patterns, impact on daily life",
  },
  {
    key: "pmh",
    label: "Past Medical History",
    abbr: "PMH",
    color: "border-l-emerald-400",
    hint: "Previous conditions, surgeries, investigations",
  },
  {
    key: "fh",
    label: "Family History",
    abbr: "FH",
    color: "border-l-amber-400",
    hint: "Relevant family history, endometriosis, gynaecological conditions",
  },
  {
    key: "sh",
    label: "Social History",
    abbr: "SH",
    color: "border-l-orange-400",
    hint: "Occupation, relationships, smoking, alcohol, impact on work",
  },
  {
    key: "allergies",
    label: "Allergies",
    abbr: "AL",
    color: "border-l-red-400",
    hint: "Known drug or food allergies",
  },
  {
    key: "drugs",
    label: "Drugs / Current Medications",
    abbr: "Rx",
    color: "border-l-teal-400",
    hint: "All current medications including contraception and supplements",
  },
];

// ── Download helper ───────────────────────────────────────────────────────────

function buildDocHtml(note: SoapNote, patientName: string, date: string): string {
  const sections = HISTORY_SECTIONS.map(
    (s) => `<h2>${s.abbr} — ${s.label}</h2><div class="section"><p>${note[s.key]}</p></div>`
  ).join("\n");

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body { font-family: Arial, sans-serif; font-size: 12pt; color: #111; max-width: 800px; margin: 40px auto; padding: 0 40px; }
  h1 { font-size: 18pt; color: #111827; border-bottom: 2px solid #0057FF; padding-bottom: 8px; }
  h2 { font-size: 13pt; color: #0057FF; margin-top: 24px; margin-bottom: 4px; }
  .meta { font-size: 10pt; color: #6B7280; margin-bottom: 24px; }
  .summary { background: #F0F4FF; border-left: 4px solid #0057FF; padding: 12px 16px; margin-bottom: 24px; font-style: italic; }
  p { line-height: 1.6; white-space: pre-wrap; }
  .section { border-left: 4px solid #E8E8E8; padding-left: 16px; margin-bottom: 20px; }
  .footer { margin-top: 40px; font-size: 9pt; color: #9CA3AF; border-top: 1px solid #E8E8E8; padding-top: 12px; }
</style>
</head>
<body>
<h1>Consultation History</h1>
<div class="meta">Patient: <strong>${patientName}</strong> &nbsp;|&nbsp; Date: ${date} &nbsp;|&nbsp; Generated by EndoLink CDSS</div>
<div class="summary">${note.summary}</div>
${sections}
<div class="footer">This document was auto-generated from a consultation recording by EndoLink CDSS. It should be reviewed and approved by the clinician before being added to the medical record. Based on NICE NG73: Endometriosis — Diagnosis and Management.</div>
</body>
</html>`;
}

function downloadDoc(note: SoapNote, patientName: string) {
  const date = new Date().toLocaleDateString("en-GB", {
    day: "numeric", month: "long", year: "numeric",
  });
  const html = buildDocHtml(note, patientName, date);
  const blob = new Blob([html], { type: "application/msword" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `ConsultationHistory_${patientName.replace(/\s+/g, "_")}_${new Date().toISOString().slice(0, 10)}.doc`;
  a.click();
  URL.revokeObjectURL(url);
}

// ── Build patient context string for AI ──────────────────────────────────────

function buildPatientContext(patient: Partial<PatientHistory> | null): string {
  if (!patient || !patient.name) return "";
  const parts: string[] = [];
  if (patient.name) parts.push(`Name: ${patient.name}`);
  if (patient.age) parts.push(`Age: ${patient.age}`);
  if (patient.symptom_duration_months) parts.push(`Symptom duration: ${patient.symptom_duration_months} months`);
  if (patient.dysmenorrhoea_severity) parts.push(`Dysmenorrhoea severity: ${patient.dysmenorrhoea_severity}/10`);
  if (patient.known_endometriosis_stage && patient.known_endometriosis_stage !== "none")
    parts.push(`Known endometriosis: ${patient.known_endometriosis_stage.replace("_", " ")}`);
  if (patient.current_treatments?.length)
    parts.push(`Current treatments: ${patient.current_treatments.join(", ")}`);
  return parts.join(" | ");
}

// ── Timer ────────────────────────────────────────────────────────────────────

function useTimer(active: boolean) {
  const [seconds, setSeconds] = useState(0);
  const ref = useRef<ReturnType<typeof setInterval> | null>(null);

  useEffect(() => {
    if (active) {
      ref.current = setInterval(() => setSeconds((s) => s + 1), 1000);
    } else {
      if (ref.current) clearInterval(ref.current);
      if (!active) setSeconds(0);
    }
    return () => { if (ref.current) clearInterval(ref.current); };
  }, [active]);

  const mm = String(Math.floor(seconds / 60)).padStart(2, "0");
  const ss = String(seconds % 60).padStart(2, "0");
  return `${mm}:${ss}`;
}

// ── Main component ────────────────────────────────────────────────────────────

interface ConsultationRecorderProps {
  patient: Partial<PatientHistory> | null;
  onSave: (note: { content: string; transcript: string; clinicalUpdates: Partial<PatientHistory> }) => void;
}

export function ConsultationRecorder({ patient, onSave }: ConsultationRecorderProps) {
  const [status, setStatus] = useState<RecordingStatus>("idle");
  const [transcript, setTranscript] = useState("");
  const [note, setNote] = useState<SoapNote | null>(null);
  const [editedNote, setEditedNote] = useState<SoapNote | null>(null);
  const [clinicalExtract, setClinicalExtract] = useState<ClinicalExtract | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [expandedSections, setExpandedSections] = useState<Record<string, boolean>>(
    Object.fromEntries(HISTORY_SECTIONS.map((s) => [s.key, true]))
  );

  const recognitionRef = useRef<SpeechRecognition | null>(null);
  const finalTextRef = useRef("");
  const timer = useTimer(status === "recording");

  const isSupported =
    typeof window !== "undefined" &&
    ("SpeechRecognition" in window || "webkitSpeechRecognition" in window);

  const startRecording = useCallback(() => {
    if (!isSupported) { setError("Speech recognition not supported. Try Chrome or Edge."); return; }

    const SR = window.SpeechRecognition ?? (window as typeof window & { webkitSpeechRecognition: typeof SpeechRecognition }).webkitSpeechRecognition;
    const rec = new SR();
    rec.lang = "en-GB";
    rec.continuous = true;
    rec.interimResults = true;

    finalTextRef.current = "";

    rec.onresult = (event) => {
      let interim = "";
      for (let i = event.resultIndex; i < event.results.length; i++) {
        if (event.results[i].isFinal) {
          finalTextRef.current += event.results[i][0].transcript + " ";
        } else {
          interim = event.results[i][0].transcript;
        }
      }
      setTranscript(finalTextRef.current + interim);
    };

    rec.onerror = (event) => {
      setError(event.error === "not-allowed"
        ? "Microphone access denied."
        : `Recording error: ${event.error}`);
      setStatus("error");
    };

    recognitionRef.current = rec;
    rec.start();
    setStatus("recording");
    setTranscript("");
    setError(null);
    setNote(null);
    setEditedNote(null);
  }, [isSupported]);

  const stopRecording = useCallback(() => {
    recognitionRef.current?.stop();
    recognitionRef.current = null;
    setStatus("stopped");
  }, []);

  async function generateNote() {
    const text = transcript.trim();
    if (!text) return;
    setStatus("generating");
    setError(null);

    try {
      const [noteRes, extractRes] = await Promise.all([
        fetch("/api/soap-note", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            transcript: text,
            patientContext: buildPatientContext(patient),
          }),
        }),
        fetch("/api/clinical-extract", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ transcript: text }),
        }),
      ]);

      if (!noteRes.ok) {
        const body = await noteRes.json().catch(() => ({}));
        throw new Error(body.error ?? "Failed to generate consultation note");
      }

      const noteData = (await noteRes.json()) as SoapNote;
      setNote(noteData);
      setEditedNote({ ...noteData });

      if (extractRes.ok) {
        const extractData = (await extractRes.json()) as ClinicalExtract;
        setClinicalExtract(extractData);
      }

      setStatus("ready");
    } catch (err) {
      setError((err as Error).message);
      setStatus("error");
    }
  }

  function handleSave() {
    if (!editedNote) return;
    const date = new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" });

    const content = [
      `CONSULTATION HISTORY — ${date}`,
      `Summary: ${editedNote.summary}`,
      "",
      ...HISTORY_SECTIONS.map((s) => `${s.abbr} — ${s.label}\n${editedNote[s.key]}`).join("\n\n").split("\n"),
    ].join("\n");

    const clinicalUpdates: Partial<PatientHistory> = {};
    if (clinicalExtract) {
      const e = clinicalExtract;
      if (e.age != null) clinicalUpdates.age = e.age;
      if (e.bmi != null) clinicalUpdates.bmi = e.bmi;
      if (e.menarche_age != null) clinicalUpdates.menarche_age = e.menarche_age;
      if (e.cycle_length_days != null) clinicalUpdates.cycle_length_days = e.cycle_length_days;
      if (e.cycle_regularity != null) clinicalUpdates.cycle_regularity = e.cycle_regularity;
      if (e.dysmenorrhoea_severity != null) clinicalUpdates.dysmenorrhoea_severity = e.dysmenorrhoea_severity;
      if (e.dysmenorrhoea_onset_age != null) clinicalUpdates.dysmenorrhoea_onset_age = e.dysmenorrhoea_onset_age;
      if (e.symptom_duration_months != null) clinicalUpdates.symptom_duration_months = e.symptom_duration_months;
      if (e.gravidity != null) clinicalUpdates.gravidity = e.gravidity;
      if (e.parity != null) clinicalUpdates.parity = e.parity;
      if (e.fertility_concerns != null) clinicalUpdates.fertility_concerns = e.fertility_concerns;
      if (e.chronic_pelvic_pain != null) clinicalUpdates.chronic_pelvic_pain = e.chronic_pelvic_pain;
      if (e.dyspareunia != null) clinicalUpdates.dyspareunia = e.dyspareunia;
      if (e.dyschezia != null) clinicalUpdates.dyschezia = e.dyschezia;
      if (e.dysuria != null) clinicalUpdates.dysuria = e.dysuria;
      if (e.cyclical_bowel_symptoms != null) clinicalUpdates.cyclical_bowel_symptoms = e.cyclical_bowel_symptoms;
      if (e.cyclical_bladder_symptoms != null) clinicalUpdates.cyclical_bladder_symptoms = e.cyclical_bladder_symptoms;
      if (e.non_cyclical_pain != null) clinicalUpdates.non_cyclical_pain = e.non_cyclical_pain;
      if (e.previous_ultrasound != null) clinicalUpdates.previous_ultrasound = e.previous_ultrasound;
      if (e.previous_laparoscopy != null) clinicalUpdates.previous_laparoscopy = e.previous_laparoscopy;
      if (e.previous_mri != null) clinicalUpdates.previous_mri = e.previous_mri;
      if (e.known_endometriosis_stage != null) clinicalUpdates.known_endometriosis_stage = e.known_endometriosis_stage;
      if (e.current_treatments != null) clinicalUpdates.current_treatments = e.current_treatments;
      if (e.family_history_endo != null) clinicalUpdates.family_history_endo = e.family_history_endo;
      if (e.comorbidities != null) clinicalUpdates.comorbidities = e.comorbidities;
    }

    onSave({ content, transcript, clinicalUpdates });
    setStatus("saved");
  }

  function reset() {
    setStatus("idle");
    setTranscript("");
    setNote(null);
    setEditedNote(null);
    setClinicalExtract(null);
    setError(null);
    finalTextRef.current = "";
  }

  function toggleSection(key: string) {
    setExpandedSections((prev) => ({ ...prev, [key]: !prev[key] }));
  }

  const patientName = patient?.name ?? "Patient";

  return (
    <Card className="bg-white border-[#E8E8E8]">
      <CardHeader className="pb-3">
        <CardTitle className="text-sm font-bold text-[var(--color-brand-midnight)] flex items-center gap-2">
          <Mic className="h-4 w-4 text-[var(--color-brand-primary)]" />
          Post-Consultation Dictation
        </CardTitle>
        <p className="text-xs text-[var(--color-brand-muted)]">
          After your consultation, press record and summarise the history in your own words — AI will populate CO, HPC, PMH, FH, SH, Allergies and Medications.
        </p>
      </CardHeader>

      <CardContent className="space-y-4">
        {/* ── Controls ── */}
        {(status === "idle" || status === "recording" || status === "stopped" || status === "error") && (
          <div className="flex items-center gap-3 flex-wrap">
            {status !== "recording" ? (
              <Button
                type="button"
                onClick={startRecording}
                className="gap-2 bg-[var(--color-brand-primary)] text-white hover:bg-[var(--color-brand-primary-hover)]"
              >
                <Mic className="h-4 w-4" />
                {status === "stopped" || status === "error" ? "Re-record" : "Start Recording"}
              </Button>
            ) : (
              <Button
                type="button"
                onClick={stopRecording}
                className="gap-2 bg-rose-600 text-white hover:bg-rose-700"
              >
                <Square className="h-4 w-4" />
                Stop Recording
              </Button>
            )}

            {status === "recording" && (
              <div className="flex items-center gap-2">
                <span className="h-2 w-2 rounded-full bg-rose-500 animate-pulse" />
                <span className="text-sm font-mono font-semibold text-rose-600">{timer}</span>
              </div>
            )}

            {status === "stopped" && transcript.trim() && (
              <Button
                type="button"
                onClick={generateNote}
                className="gap-2 bg-[#111827] text-white hover:bg-[#1F2937]"
              >
                <Sparkles className="h-4 w-4" />
                Generate History
              </Button>
            )}

            {(status === "stopped" || status === "error") && (
              <button type="button" onClick={reset} className="text-xs text-[var(--color-brand-muted)] hover:text-[var(--color-brand-midnight)] flex items-center gap-1">
                <RotateCcw className="h-3 w-3" /> Reset
              </button>
            )}
          </div>
        )}

        {/* ── Generating spinner ── */}
        {status === "generating" && (
          <div className="flex items-center gap-3 py-2">
            <span className="h-5 w-5 rounded-full border-2 border-[var(--color-brand-primary)] border-t-transparent animate-spin shrink-0" />
            <p className="text-sm text-[var(--color-brand-muted)]">
              Analysing transcript and populating clinical history…
            </p>
          </div>
        )}

        {/* ── Error ── */}
        {error && (
          <div className="flex items-start gap-2 rounded-lg bg-red-50 border border-red-100 px-3 py-2.5">
            <AlertCircle className="h-4 w-4 text-red-500 shrink-0 mt-0.5" />
            <p className="text-xs text-red-700">{error}</p>
          </div>
        )}

        {/* ── Live transcript ── */}
        {transcript && status !== "saved" && (
          <div>
            <p className="text-xs font-semibold text-[var(--color-brand-muted)] uppercase tracking-wide mb-1.5">
              {status === "recording" ? "Dictating…" : "Dictation"}
            </p>
            <div className="rounded-lg bg-[var(--color-brand-smoke)] border border-[#E8E8E8] px-4 py-3 max-h-40 overflow-y-auto">
              <p className="text-sm text-[var(--color-brand-midnight)] leading-relaxed whitespace-pre-wrap">
                {transcript}
              </p>
            </div>
            {status === "stopped" && (
              <p className="text-xs text-[var(--color-brand-muted)] mt-1">
                {transcript.split(/\s+/).filter(Boolean).length} words recorded
              </p>
            )}
          </div>
        )}

        {/* ── Clinical history sections ── */}
        {(status === "ready" || status === "saved") && editedNote && (
          <div className="space-y-3">
            <Separator />

            {/* Summary */}
            <div className="rounded-lg bg-[var(--color-brand-primary)]/5 border border-[var(--color-brand-primary)]/20 px-4 py-3">
              <p className="text-xs font-bold text-[var(--color-brand-primary)] mb-1 uppercase tracking-wide">
                Summary
              </p>
              <p className="text-sm text-[var(--color-brand-midnight)] leading-relaxed italic">
                {editedNote.summary}
              </p>
            </div>

            {/* History sections */}
            {HISTORY_SECTIONS.map(({ key, label, abbr, color, hint }) => (
              <div key={key} className={`border-l-4 pl-4 ${color}`}>
                <button
                  type="button"
                  onClick={() => toggleSection(key)}
                  className="flex items-center justify-between w-full text-left mb-1.5"
                >
                  <div>
                    <span className="text-xs font-bold text-[var(--color-brand-midnight)] uppercase tracking-wide">
                      {abbr} — {label}
                    </span>
                    <p className="text-xs text-[var(--color-brand-muted)] font-normal normal-case tracking-normal">{hint}</p>
                  </div>
                  {expandedSections[key]
                    ? <ChevronUp className="h-3.5 w-3.5 text-[var(--color-brand-muted)] shrink-0 ml-2" />
                    : <ChevronDown className="h-3.5 w-3.5 text-[var(--color-brand-muted)] shrink-0 ml-2" />
                  }
                </button>
                {expandedSections[key] && (
                  <Textarea
                    value={editedNote[key]}
                    onChange={(e) => setEditedNote((prev) => prev ? { ...prev, [key]: e.target.value } : prev)}
                    rows={3}
                    className="text-sm border-[#E8E8E8] resize-y bg-white"
                    disabled={status === "saved"}
                  />
                )}
              </div>
            ))}

            {/* Auto-populated fields chip */}
            {status === "ready" && clinicalExtract && (() => {
              const fields: string[] = [];
              const e = clinicalExtract;
              if (e.age != null) fields.push(`Age: ${e.age}`);
              if (e.dysmenorrhoea_severity != null) fields.push(`Dysmenorrhoea: ${e.dysmenorrhoea_severity}/10`);
              if (e.symptom_duration_months != null) fields.push(`Duration: ${e.symptom_duration_months}mo`);
              if (e.chronic_pelvic_pain) fields.push("Pelvic pain");
              if (e.dyspareunia) fields.push("Dyspareunia");
              if (e.dyschezia) fields.push("Dyschezia");
              if (e.fertility_concerns) fields.push("Fertility concerns");
              if (e.family_history_endo) fields.push("Family Hx endo");
              if (e.previous_laparoscopy) fields.push("Prior laparoscopy");
              if (!fields.length) return null;
              return (
                <div className="rounded-lg bg-emerald-50 border border-emerald-200 px-3 py-2.5">
                  <p className="text-xs font-semibold text-emerald-800 mb-1.5 flex items-center gap-1.5">
                    <Sparkles className="h-3.5 w-3.5" />
                    Clinical record will be auto-updated
                  </p>
                  <div className="flex flex-wrap gap-1.5">
                    {fields.map((f) => (
                      <span key={f} className="text-xs bg-emerald-100 text-emerald-800 px-2 py-0.5 rounded-full">{f}</span>
                    ))}
                  </div>
                </div>
              );
            })()}

            {/* Actions */}
            {status === "ready" && (
              <div className="flex items-center gap-2 pt-1 flex-wrap">
                <Button
                  type="button"
                  onClick={handleSave}
                  className="gap-2 bg-[var(--color-brand-primary)] text-white hover:bg-[var(--color-brand-primary-hover)]"
                >
                  <Save className="h-4 w-4" />
                  Save to Patient Record
                </Button>
                <Button
                  type="button"
                  variant="outline"
                  onClick={() => downloadDoc(editedNote, patientName)}
                  className="gap-2 border-[#E8E8E8]"
                >
                  <Download className="h-4 w-4" />
                  Download .doc
                </Button>
                <button
                  type="button"
                  onClick={reset}
                  className="text-xs text-[var(--color-brand-muted)] hover:text-[var(--color-brand-midnight)] flex items-center gap-1 ml-auto"
                >
                  <RotateCcw className="h-3 w-3" /> Start over
                </button>
              </div>
            )}

            {status === "saved" && (
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2 text-emerald-700">
                  <CheckCircle2 className="h-4 w-4" />
                  <span className="text-sm font-semibold">Saved to consultation notes</span>
                </div>
                <div className="flex items-center gap-2">
                  <Button
                    type="button"
                    variant="outline"
                    size="sm"
                    onClick={() => downloadDoc(editedNote, patientName)}
                    className="gap-1.5 border-[#E8E8E8] h-8 text-xs"
                  >
                    <Download className="h-3.5 w-3.5" />
                    Download
                  </Button>
                  <button
                    type="button"
                    onClick={reset}
                    className="text-xs text-[var(--color-brand-muted)] hover:text-[var(--color-brand-midnight)] flex items-center gap-1"
                  >
                    <FileText className="h-3 w-3" /> New dictation
                  </button>
                </div>
              </div>
            )}

            <p className="text-xs text-[var(--color-brand-muted)] leading-relaxed pt-1">
              AI-generated from your dictation — review and edit before saving to the medical record.
            </p>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
