"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import {
  AlertCircle,
  CheckCircle2,
  Download,
  FileText,
  Mic,
  RotateCcw,
  Save,
  Sparkles,
  Square,
} from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { cn } from "@/lib/utils";
import type { SoapNote } from "@/app/api/soap-note/route";
import type { PatientHistory } from "@/lib/types/cdss";

// ── Recording status ──────────────────────────────────────────────────────────

type RecordingStatus =
  | "idle"
  | "recording"
  | "stopped"
  | "generating"
  | "ready"
  | "saved"
  | "error";

// ── SOAP section config ───────────────────────────────────────────────────────

const SOAP_SECTIONS: { key: keyof SoapNote; label: string; color: string }[] = [
  { key: "subjective",  label: "S — Subjective",  color: "border-l-blue-400" },
  { key: "objective",   label: "O — Objective",   color: "border-l-emerald-400" },
  { key: "assessment",  label: "A — Assessment",  color: "border-l-amber-400" },
  { key: "plan",        label: "P — Plan",        color: "border-l-purple-400" },
];

// ── Download helper ───────────────────────────────────────────────────────────

function buildDocHtml(soap: SoapNote, patientName: string, date: string): string {
  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body { font-family: Arial, sans-serif; font-size: 12pt; color: #111; max-width: 800px; margin: 40px auto; padding: 0 40px; }
  h1 { font-size: 18pt; color: #111827; border-bottom: 2px solid #0057FF; padding-bottom: 8px; }
  h2 { font-size: 13pt; color: #0057FF; margin-top: 24px; margin-bottom: 4px; }
  .meta { font-size: 10pt; color: #6B7280; margin-bottom: 24px; }
  .summary { background: #F0F4FF; border-left: 4px solid #0057FF; padding: 12px 16px; margin-bottom: 24px; font-style: italic; }
  p { line-height: 1.6; white-space: pre-wrap; }
  .section { border-left: 4px solid #E8E8E8; padding-left: 16px; margin-bottom: 20px; }
  .footer { margin-top: 40px; font-size: 9pt; color: #9CA3AF; border-top: 1px solid #E8E8E8; padding-top: 12px; }
</style>
</head>
<body>
<h1>Consultation SOAP Note</h1>
<div class="meta">Patient: <strong>${patientName}</strong> &nbsp;|&nbsp; Date: ${date} &nbsp;|&nbsp; Generated by EndoLink CDSS</div>
<div class="summary">${soap.summary}</div>
<h2>Subjective</h2>
<div class="section"><p>${soap.subjective}</p></div>
<h2>Objective</h2>
<div class="section"><p>${soap.objective}</p></div>
<h2>Assessment</h2>
<div class="section"><p>${soap.assessment}</p></div>
<h2>Plan</h2>
<div class="section"><p>${soap.plan}</p></div>
<div class="footer">This document was auto-generated from a consultation recording by EndoLink CDSS. It should be reviewed and approved by the clinician before being added to the medical record. Based on NICE NG73: Endometriosis — Diagnosis and Management.</div>
</body>
</html>`;
}

function downloadDoc(soap: SoapNote, patientName: string) {
  const date = new Date().toLocaleDateString("en-GB", {
    day: "numeric", month: "long", year: "numeric",
  });
  const html = buildDocHtml(soap, patientName, date);
  const blob = new Blob([html], { type: "application/msword" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `SOAP_${patientName.replace(/\s+/g, "_")}_${new Date().toISOString().slice(0, 10)}.doc`;
  a.click();
  URL.revokeObjectURL(url);
}

// ── Build patient context string for AI ──────────────────────────────────────

function buildPatientContext(patient: Partial<PatientHistory> | null): string {
  if (!patient || !patient.name) return "";
  const parts: string[] = [];
  if (patient.name) parts.push(`Name: ${patient.name}`);
  if (patient.age) parts.push(`Age: ${patient.age}`);
  if (patient.symptom_duration_months) parts.push(`Symptom duration: ${patient.symptom_duration_months} months`);
  if (patient.dysmenorrhoea_severity) parts.push(`Dysmenorrhoea severity: ${patient.dysmenorrhoea_severity}/10`);
  if (patient.known_endometriosis_stage && patient.known_endometriosis_stage !== "none")
    parts.push(`Known endometriosis: ${patient.known_endometriosis_stage.replace("_", " ")}`);
  if (patient.current_treatments?.length)
    parts.push(`Current treatments: ${patient.current_treatments.join(", ")}`);
  return parts.join(" | ");
}

// ── Timer ────────────────────────────────────────────────────────────────────

function useTimer(active: boolean) {
  const [seconds, setSeconds] = useState(0);
  const ref = useRef<ReturnType<typeof setInterval> | null>(null);

  useEffect(() => {
    if (active) {
      ref.current = setInterval(() => setSeconds((s) => s + 1), 1000);
    } else {
      if (ref.current) clearInterval(ref.current);
      if (!active) setSeconds(0);
    }
    return () => { if (ref.current) clearInterval(ref.current); };
  }, [active]);

  const mm = String(Math.floor(seconds / 60)).padStart(2, "0");
  const ss = String(seconds % 60).padStart(2, "0");
  return `${mm}:${ss}`;
}

// ── Main component ────────────────────────────────────────────────────────────

interface ConsultationRecorderProps {
  patient: Partial<PatientHistory> | null;
  onSave: (note: { content: string; transcript: string }) => void;
}

export function ConsultationRecorder({ patient, onSave }: ConsultationRecorderProps) {
  const [status, setStatus] = useState<RecordingStatus>("idle");
  const [transcript, setTranscript] = useState("");
  const [soap, setSoap] = useState<SoapNote | null>(null);
  const [editedSoap, setEditedSoap] = useState<SoapNote | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [expandedSections, setExpandedSections] = useState<Record<string, boolean>>({
    subjective: true, objective: true, assessment: true, plan: true,
  });

  const recognitionRef = useRef<SpeechRecognition | null>(null);
  const finalTextRef = useRef("");
  const timer = useTimer(status === "recording");

  const isSupported =
    typeof window !== "undefined" &&
    ("SpeechRecognition" in window || "webkitSpeechRecognition" in window);

  const startRecording = useCallback(() => {
    if (!isSupported) { setError("Speech recognition not supported. Try Chrome or Edge."); return; }

    const SR = window.SpeechRecognition ?? (window as typeof window & { webkitSpeechRecognition: typeof SpeechRecognition }).webkitSpeechRecognition;
    const rec = new SR();
    rec.lang = "en-GB";
    rec.continuous = true;
    rec.interimResults = true;

    finalTextRef.current = "";

    rec.onresult = (event) => {
      let interim = "";
      for (let i = event.resultIndex; i < event.results.length; i++) {
        if (event.results[i].isFinal) {
          finalTextRef.current += event.results[i][0].transcript + " ";
        } else {
          interim = event.results[i][0].transcript;
        }
      }
      setTranscript(finalTextRef.current + interim);
    };

    rec.onerror = (event) => {
      setError(event.error === "not-allowed"
        ? "Microphone access denied."
        : `Recording error: ${event.error}`);
      setStatus("error");
    };

    recognitionRef.current = rec;
    rec.start();
    setStatus("recording");
    setTranscript("");
    setError(null);
    setSoap(null);
    setEditedSoap(null);
  }, [isSupported]);

  const stopRecording = useCallback(() => {
    recognitionRef.current?.stop();
    recognitionRef.current = null;
    setStatus("stopped");
  }, []);

  async function generateSoap() {
    const text = transcript.trim();
    if (!text) return;
    setStatus("generating");
    setError(null);

    try {
      const res = await fetch("/api/soap-note", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          transcript: text,
          patientContext: buildPatientContext(patient),
        }),
      });

      if (!res.ok) {
        const body = await res.json().catch(() => ({}));
        throw new Error(body.error ?? "Failed to generate SOAP note");
      }

      const data = (await res.json()) as SoapNote;
      setSoap(data);
      setEditedSoap({ ...data });
      setStatus("ready");
    } catch (err) {
      setError((err as Error).message);
      setStatus("error");
    }
  }

  function handleSave() {
    if (!editedSoap) return;
    const content = [
      `SOAP NOTE — ${new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}`,
      `Summary: ${editedSoap.summary}`,
      "",
      `SUBJECTIVE\n${editedSoap.subjective}`,
      "",
      `OBJECTIVE\n${editedSoap.objective}`,
      "",
      `ASSESSMENT\n${editedSoap.assessment}`,
      "",
      `PLAN\n${editedSoap.plan}`,
    ].join("\n");

    onSave({ content, transcript });
    setStatus("saved");
  }

  function reset() {
    setStatus("idle");
    setTranscript("");
    setSoap(null);
    setEditedSoap(null);
    setError(null);
    finalTextRef.current = "";
  }

  function toggleSection(key: string) {
    setExpandedSections((prev) => ({ ...prev, [key]: !prev[key] }));
  }

  const patientName = patient?.name ?? "Patient";

  return (
    <Card className="bg-white border-[#E8E8E8]">
      <CardHeader className="pb-3">
        <CardTitle className="text-sm font-bold text-[var(--color-brand-midnight)] flex items-center gap-2">
          <Mic className="h-4 w-4 text-[var(--color-brand-primary)]" />
          Consultation Recording
        </CardTitle>
        <p className="text-xs text-[var(--color-brand-muted)]">
          Record the session. AI will transcribe and generate a SOAP note you can edit and save to the patient record.
        </p>
      </CardHeader>

      <CardContent className="space-y-4">
        {/* ── Controls ── */}
        {(status === "idle" || status === "recording" || status === "stopped" || status === "error") && (
          <div className="flex items-center gap-3">
            {status !== "recording" ? (
              <Button
                type="button"
                onClick={startRecording}
                className="gap-2 bg-[var(--color-brand-primary)] text-white hover:bg-[var(--color-brand-primary-hover)]"
              >
                <Mic className="h-4 w-4" />
                {status === "stopped" || status === "error" ? "Re-record" : "Start Recording"}
              </Button>
            ) : (
              <Button
                type="button"
                onClick={stopRecording}
                className="gap-2 bg-rose-600 text-white hover:bg-rose-700"
              >
                <Square className="h-4 w-4" />
                Stop Recording
              </Button>
            )}

            {status === "recording" && (
              <div className="flex items-center gap-2">
                <span className="h-2 w-2 rounded-full bg-rose-500 animate-pulse" />
                <span className="text-sm font-mono font-semibold text-rose-600">{timer}</span>
              </div>
            )}

            {status === "stopped" && transcript.trim() && (
              <Button
                type="button"
                onClick={generateSoap}
                className="gap-2 bg-[#111827] text-white hover:bg-[#1F2937]"
              >
                <Sparkles className="h-4 w-4" />
                Generate SOAP Note
              </Button>
            )}

            {(status === "stopped" || status === "error") && (
              <button type="button" onClick={reset} className="text-xs text-[var(--color-brand-muted)] hover:text-[var(--color-brand-midnight)] flex items-center gap-1">
                <RotateCcw className="h-3 w-3" /> Reset
              </button>
            )}
          </div>
        )}

        {/* ── Generating spinner ── */}
        {status === "generating" && (
          <div className="flex items-center gap-3 py-2">
            <span className="h-5 w-5 rounded-full border-2 border-[var(--color-brand-primary)] border-t-transparent animate-spin shrink-0" />
            <p className="text-sm text-[var(--color-brand-muted)]">
              Analysing transcript and generating SOAP note…
            </p>
          </div>
        )}

        {/* ── Error ── */}
        {error && (
          <div className="flex items-start gap-2 rounded-lg bg-red-50 border border-red-100 px-3 py-2.5">
            <AlertCircle className="h-4 w-4 text-red-500 shrink-0 mt-0.5" />
            <p className="text-xs text-red-700">{error}</p>
          </div>
        )}

        {/* ── Live transcript ── */}
        {transcript && status !== "saved" && (
          <div>
            <p className="text-xs font-semibold text-[var(--color-brand-muted)] uppercase tracking-wide mb-1.5">
              {status === "recording" ? "Live transcript" : "Transcript"}
            </p>
            <div className="rounded-lg bg-[var(--color-brand-smoke)] border border-[#E8E8E8] px-4 py-3 max-h-40 overflow-y-auto">
              <p className="text-sm text-[var(--color-brand-midnight)] leading-relaxed whitespace-pre-wrap">
                {transcript}
              </p>
            </div>
            {status === "stopped" && (
              <p className="text-xs text-[var(--color-brand-muted)] mt-1">
                {transcript.split(/\s+/).filter(Boolean).length} words recorded
              </p>
            )}
          </div>
        )}

        {/* ── SOAP note ── */}
        {(status === "ready" || status === "saved") && editedSoap && (
          <div className="space-y-3">
            <Separator />

            {/* Summary */}
            <div className="rounded-lg bg-[var(--color-brand-primary)]/5 border border-[var(--color-brand-primary)]/20 px-4 py-3">
              <p className="text-xs font-bold text-[var(--color-brand-primary)] mb-1 uppercase tracking-wide">
                Summary
              </p>
              <p className="text-sm text-[var(--color-brand-midnight)] leading-relaxed italic">
                {editedSoap.summary}
              </p>
            </div>

            {/* SOAP sections */}
            {SOAP_SECTIONS.map(({ key, label, color }) => (
              <div key={key} className={`border-l-4 pl-4 ${color}`}>
                <button
                  type="button"
                  onClick={() => toggleSection(key)}
                  className="flex items-center justify-between w-full text-left mb-1.5"
                >
                  <span className="text-xs font-bold text-[var(--color-brand-midnight)] uppercase tracking-wide">
                    {label}
                  </span>
                  {expandedSections[key]
                    ? <ChevronUp className="h-3.5 w-3.5 text-[var(--color-brand-muted)]" />
                    : <ChevronDown className="h-3.5 w-3.5 text-[var(--color-brand-muted)]" />
                  }
                </button>
                {expandedSections[key] && (
                  <Textarea
                    value={editedSoap[key]}
                    onChange={(e) => setEditedSoap((prev) => prev ? { ...prev, [key]: e.target.value } : prev)}
                    rows={4}
                    className="text-sm border-[#E8E8E8] resize-y bg-white"
                    disabled={status === "saved"}
                  />
                )}
              </div>
            ))}

            {/* Actions */}
            {status === "ready" && (
              <div className="flex items-center gap-2 pt-1 flex-wrap">
                <Button
                  type="button"
                  onClick={handleSave}
                  className="gap-2 bg-[var(--color-brand-primary)] text-white hover:bg-[var(--color-brand-primary-hover)]"
                >
                  <Save className="h-4 w-4" />
                  Save to Patient Record
                </Button>
                <Button
                  type="button"
                  variant="outline"
                  onClick={() => downloadDoc(editedSoap, patientName)}
                  className="gap-2 border-[#E8E8E8]"
                >
                  <Download className="h-4 w-4" />
                  Download .doc
                </Button>
                <button
                  type="button"
                  onClick={reset}
                  className="text-xs text-[var(--color-brand-muted)] hover:text-[var(--color-brand-midnight)] flex items-center gap-1 ml-auto"
                >
                  <RotateCcw className="h-3 w-3" /> Start over
                </button>
              </div>
            )}

            {status === "saved" && (
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2 text-emerald-700">
                  <CheckCircle2 className="h-4 w-4" />
                  <span className="text-sm font-semibold">Saved to consultation notes</span>
                </div>
                <div className="flex items-center gap-2">
                  <Button
                    type="button"
                    variant="outline"
                    size="sm"
                    onClick={() => downloadDoc(editedSoap, patientName)}
                    className="gap-1.5 border-[#E8E8E8] h-8 text-xs"
                  >
                    <Download className="h-3.5 w-3.5" />
                    Download
                  </Button>
                  <button
                    type="button"
                    onClick={reset}
                    className="text-xs text-[var(--color-brand-muted)] hover:text-[var(--color-brand-midnight)] flex items-center gap-1"
                  >
                    <FileText className="h-3 w-3" /> New recording
                  </button>
                </div>
              </div>
            )}

            {/* AI disclaimer */}
            <p className="text-xs text-[var(--color-brand-muted)] leading-relaxed pt-1">
              AI-generated — review and edit before saving to the medical record.
            </p>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
