-- Endo: cached Cumulative Symptom Dossier renders.
--
-- The CSD is generated by the LLM gateway in two audiences (patient,
-- clinician) from a single typed payload (CSDPayload). For byte-stable
-- exports (the brief calls for byte-stable PDFs over unchanged input),
-- we cache rendered narratives keyed on the SHA-256 hash of the
-- canonical-JSON-serialised payload. If the same payload is rendered
-- twice, the second render returns the cached row and produces an
-- identical PDF without a fresh model call.
--
-- Caching is per-patient + per-audience + per-payload-hash. A new entry
-- is inserted on every fresh render; old entries are kept (audit trail).
-- The "current" render for a patient + audience is the most recent row
-- whose payload_hash matches the current payload.

create table public.csd_renders (
  id uuid primary key default uuid_generate_v4(),
  created_at timestamptz not null default now(),

  patient_subject_id uuid not null references auth.users(id) on delete cascade,
  audience text not null check (audience in ('patient', 'clinician')),

  -- SHA-256 of the canonical JSON payload that produced this render.
  -- Same hash + same audience => byte-stable narrative (and PDF).
  payload_hash text not null,

  -- The structured payload itself, retained for replay and for the
  -- per-claim source-resolver UI.
  payload jsonb not null,

  -- Rendered narrative + parsed citations.
  body text not null,
  citations jsonb not null default '[]'::jsonb,

  -- Provenance — same shape as journal_entries.
  model_id text not null,
  prompt_template_version text not null,
  audit_entry_id uuid references public.llm_audit_log(id) on delete set null,

  -- Outcome of the generation. Most rows are 'success'; refused or
  -- linter-blocked renders are kept for audit but never returned to UI.
  outcome text not null check (outcome in (
    'success',
    'refused_diagnostic_conclusion',
    'banned_term_lint',
    'validation_failed',
    'model_error'
  ))
);

create index idx_csd_renders_patient_audience_recent
  on public.csd_renders(patient_subject_id, audience, created_at desc);

create index idx_csd_renders_payload_hash
  on public.csd_renders(patient_subject_id, audience, payload_hash, created_at desc);

alter table public.csd_renders enable row level security;

-- Patients read their own renders.
create policy "Patients read own CSD renders"
  on public.csd_renders for select
  using (auth.uid() = patient_subject_id);

-- Clinicians read renders for patients they hold an active consent for.
create policy "Clinicians read consented CSD renders"
  on public.csd_renders for select
  using (
    exists (
      select 1 from public.consent_tokens c
      where c.patient_subject_id = public.csd_renders.patient_subject_id
        and c.clinician_subject_id = auth.uid()
        and c.revoked_at is null
        and c.expires_at > now()
    )
  );

-- Inserts go through the service-role client only — never directly from
-- application code. There is no insert policy. Updates and deletes are
-- prohibited at the policy level (no policies created for them).
